// Emoji Detective puzzle bank. Decode the emoji(s) and type the answer.
// G-rated and guessable for ages 5–12. `alt` lists accepted spellings;
// matching ignores case, spaces and punctuation (see GuessRace normalize).

export interface EmojiPuzzle {
  emoji: string;
  answer: string;
  alt?: string[];
  hint: string;
}

export const EMOJI_PUZZLES: EmojiPuzzle[] = [
  // --- Single-emoji animals (easy warm-ups) ---
  { emoji: '🐝', answer: 'bee', hint: 'a buzzing insect' },
  { emoji: '🐱', answer: 'cat', hint: 'says meow' },
  { emoji: '🐶', answer: 'dog', hint: 'man’s best friend' },
  { emoji: '🦁', answer: 'lion', hint: 'king of the jungle' },
  { emoji: '🐯', answer: 'tiger', hint: 'big orange cat with stripes' },
  { emoji: '🐧', answer: 'penguin', hint: 'a bird that cannot fly' },
  { emoji: '🐘', answer: 'elephant', hint: 'has a trunk' },
  { emoji: '🦒', answer: 'giraffe', hint: 'very long neck' },
  { emoji: '🐸', answer: 'frog', hint: 'green and hops' },
  { emoji: '🦊', answer: 'fox', hint: 'a clever orange animal' },
  { emoji: '🐼', answer: 'panda', hint: 'black and white, loves bamboo' },
  { emoji: '🐙', answer: 'octopus', hint: 'has eight arms' },
  { emoji: '🦈', answer: 'shark', hint: 'sharp teeth in the sea' },
  { emoji: '🐬', answer: 'dolphin', hint: 'a friendly sea animal' },
  { emoji: '🦋', answer: 'butterfly', hint: 'used to be a caterpillar' },
  { emoji: '🐢', answer: 'turtle', alt: ['tortoise'], hint: 'carries its home on its back' },
  { emoji: '🐍', answer: 'snake', hint: 'long and slithers' },
  { emoji: '🐰', answer: 'rabbit', alt: ['bunny'], hint: 'hops and loves carrots' },
  { emoji: '🐴', answer: 'horse', hint: 'you can ride it, says neigh' },
  { emoji: '🐮', answer: 'cow', hint: 'says moo and gives milk' },
  { emoji: '🐷', answer: 'pig', hint: 'pink and says oink' },
  { emoji: '🦉', answer: 'owl', hint: 'a wise bird, awake at night' },
  { emoji: '🦄', answer: 'unicorn', hint: 'a magical horse with a horn' },
  { emoji: '🐳', answer: 'whale', hint: 'the biggest animal in the ocean' },
  { emoji: '🦓', answer: 'zebra', hint: 'a horse with stripes' },
  { emoji: '🦘', answer: 'kangaroo', hint: 'hops and has a pouch' },

  // --- Single-emoji food ---
  { emoji: '🍕', answer: 'pizza', hint: 'round, cheesy, with slices' },
  { emoji: '🍔', answer: 'burger', alt: ['hamburger'], hint: 'a bun with a patty' },
  { emoji: '🍟', answer: 'fries', alt: ['chips', 'french fries'], hint: 'golden potato sticks' },
  { emoji: '🌭', answer: 'hotdog', hint: 'sausage in a bun' },
  { emoji: '🍦', answer: 'ice cream', alt: ['icecream'], hint: 'cold and sweet on a cone' },
  { emoji: '🍩', answer: 'donut', alt: ['doughnut'], hint: 'sweet ring with sprinkles' },
  { emoji: '🍪', answer: 'cookie', alt: ['biscuit'], hint: 'goes with milk' },
  { emoji: '🎂', answer: 'cake', alt: ['birthday cake'], hint: 'has candles on your birthday' },
  { emoji: '🍎', answer: 'apple', hint: 'keeps the doctor away' },
  { emoji: '🍌', answer: 'banana', hint: 'yellow, monkeys love it' },
  { emoji: '🍓', answer: 'strawberry', hint: 'red with little seeds' },
  { emoji: '🍉', answer: 'watermelon', hint: 'green outside, pink inside' },
  { emoji: '🍇', answer: 'grapes', alt: ['grape'], hint: 'small and grow in bunches' },
  { emoji: '🥕', answer: 'carrot', hint: 'orange, rabbits love it' },
  { emoji: '🌽', answer: 'corn', alt: ['sweetcorn'], hint: 'yellow on the cob' },
  { emoji: '🍿', answer: 'popcorn', hint: 'a snack at the cinema' },
  { emoji: '🍭', answer: 'lollipop', alt: ['lolly'], hint: 'a sweet on a stick' },
  { emoji: '🧁', answer: 'cupcake', hint: 'a tiny cake with frosting' },
  { emoji: '🍫', answer: 'chocolate', hint: 'sweet and brown, can melt' },
  { emoji: '🍯', answer: 'honey', hint: 'bees make it' },

  // --- Single-emoji nature & objects ---
  { emoji: '🌈', answer: 'rainbow', hint: 'seven colours after the rain' },
  { emoji: '☀️', answer: 'sun', hint: 'shines in the day' },
  { emoji: '🌙', answer: 'moon', hint: 'glows in the night sky' },
  { emoji: '⭐', answer: 'star', hint: 'twinkles at night' },
  { emoji: '☁️', answer: 'cloud', hint: 'fluffy and white in the sky' },
  { emoji: '⛄', answer: 'snowman', hint: 'made of snow with a carrot nose' },
  { emoji: '🌋', answer: 'volcano', hint: 'a mountain that erupts' },
  { emoji: '🌊', answer: 'wave', hint: 'water moving at the beach' },
  { emoji: '🌳', answer: 'tree', hint: 'has leaves and a trunk' },
  { emoji: '🌸', answer: 'flower', alt: ['blossom'], hint: 'grows in a garden, smells nice' },
  { emoji: '🍄', answer: 'mushroom', hint: 'grows in the forest, has a cap' },
  { emoji: '🌵', answer: 'cactus', hint: 'a spiky desert plant' },
  { emoji: '⚡', answer: 'lightning', hint: 'a flash in a storm' },
  { emoji: '❄️', answer: 'snowflake', alt: ['snow'], hint: 'falls in winter, all different' },
  { emoji: '🔥', answer: 'fire', hint: 'hot and bright, never touch it' },
  { emoji: '🏝️', answer: 'island', hint: 'land surrounded by sea' },
  { emoji: '🌍', answer: 'earth', alt: ['world', 'planet'], hint: 'the planet we live on' },
  { emoji: '🍀', answer: 'clover', alt: ['four leaf clover', 'shamrock'], hint: 'lucky green leaves' },

  // --- Single-emoji vehicles & things ---
  { emoji: '🚗', answer: 'car', hint: 'four wheels, you drive it' },
  { emoji: '🚌', answer: 'bus', hint: 'carries lots of people' },
  { emoji: '🚂', answer: 'train', hint: 'runs on tracks, choo choo' },
  { emoji: '✈️', answer: 'airplane', alt: ['plane', 'aeroplane'], hint: 'flies in the sky' },
  { emoji: '🚀', answer: 'rocket', hint: 'blasts off into space' },
  { emoji: '🚲', answer: 'bicycle', alt: ['bike'], hint: 'two wheels and pedals' },
  { emoji: '🚁', answer: 'helicopter', hint: 'flies with spinning blades' },
  { emoji: '⛵', answer: 'sailboat', alt: ['boat'], hint: 'floats with a sail' },
  { emoji: '🚓', answer: 'police car', alt: ['police'], hint: 'catches bad guys' },
  { emoji: '🚒', answer: 'fire truck', alt: ['firetruck'], hint: 'rushes to put out fires' },
  { emoji: '🛹', answer: 'skateboard', hint: 'roll and do tricks on it' },
  { emoji: '⚓', answer: 'anchor', hint: 'keeps a ship in place' },
  { emoji: '🎈', answer: 'balloon', hint: 'fill it with air, it can pop' },
  { emoji: '🪁', answer: 'kite', hint: 'flies on a string in the wind' },
  { emoji: '🎁', answer: 'present', alt: ['gift'], hint: 'wrapped with a bow' },
  { emoji: '👑', answer: 'crown', hint: 'a king or queen wears it' },
  { emoji: '💎', answer: 'diamond', alt: ['gem', 'jewel'], hint: 'a sparkly precious stone' },
  { emoji: '🔑', answer: 'key', hint: 'opens a lock' },
  { emoji: '💡', answer: 'light bulb', alt: ['bulb', 'idea', 'lightbulb'], hint: 'lights up, or a bright idea' },
  { emoji: '✏️', answer: 'pencil', hint: 'you write with it' },
  { emoji: '✂️', answer: 'scissors', hint: 'used to cut paper' },
  { emoji: '📚', answer: 'books', alt: ['book'], hint: 'you read them' },
  { emoji: '🧩', answer: 'puzzle', alt: ['jigsaw'], hint: 'pieces that fit together' },
  { emoji: '🎨', answer: 'painting', alt: ['art', 'paint', 'palette'], hint: 'made with a brush and colours' },
  { emoji: '🏰', answer: 'castle', hint: 'where a king and queen live' },
  { emoji: '🎸', answer: 'guitar', hint: 'a music instrument with strings' },
  { emoji: '🥁', answer: 'drum', alt: ['drums'], hint: 'you bang it to make a beat' },
  { emoji: '🎹', answer: 'piano', alt: ['keyboard'], hint: 'black and white keys' },
  { emoji: '🎤', answer: 'microphone', alt: ['mic', 'singing'], hint: 'you sing into it' },
  { emoji: '🎧', answer: 'headphones', hint: 'wear them to listen to music' },
  { emoji: '🎺', answer: 'trumpet', hint: 'a shiny instrument you blow' },
  { emoji: '🎻', answer: 'violin', hint: 'play it with a bow' },
  { emoji: '⚽', answer: 'soccer ball', alt: ['football', 'soccer'], hint: 'kick it into a goal' },
  { emoji: '🏀', answer: 'basketball', hint: 'bounce it and shoot a hoop' },
  { emoji: '🎾', answer: 'tennis', alt: ['tennis ball'], hint: 'hit it with a racquet' },
  { emoji: '🏈', answer: 'football', alt: ['american football'], hint: 'an oval ball you throw' },
  { emoji: '⚾', answer: 'baseball', hint: 'hit it with a bat and run bases' },
  { emoji: '🎳', answer: 'bowling', hint: 'roll a ball to knock down pins' },
  { emoji: '🏆', answer: 'trophy', hint: 'a prize for winning' },
  { emoji: '🥇', answer: 'gold medal', alt: ['medal', 'first place'], hint: 'first place prize' },
  { emoji: '🎯', answer: 'dartboard', alt: ['target', 'bullseye'], hint: 'aim for the centre' },
  { emoji: '🧦', answer: 'sock', alt: ['socks'], hint: 'goes on your foot' },
  { emoji: '👟', answer: 'shoe', alt: ['sneaker', 'trainer'], hint: 'goes on your feet' },
  { emoji: '🧤', answer: 'gloves', hint: 'keep your hands warm' },
  { emoji: '👒', answer: 'hat', hint: 'goes on your head' },
  { emoji: '🌂', answer: 'umbrella', hint: 'keeps you dry in the rain' },
  { emoji: '🦷', answer: 'tooth', alt: ['teeth'], hint: 'the tooth fairy wants it' },
  { emoji: '👁️', answer: 'eye', hint: 'you see with it' },
  { emoji: '🧠', answer: 'brain', hint: 'you think with it' },
  { emoji: '❤️', answer: 'heart', alt: ['love'], hint: 'red and means love' },
  { emoji: '🦖', answer: 'dinosaur', alt: ['t-rex', 'trex', 'tyrannosaurus'], hint: 'lived long, long ago' },
  { emoji: '🧸', answer: 'teddy bear', alt: ['teddy', 'bear'], hint: 'a soft toy to cuddle' },
  { emoji: '🎃', answer: 'pumpkin', alt: ['jack o lantern'], hint: 'carved at Halloween' },
  { emoji: '🌻', answer: 'sunflower', hint: 'tall yellow flower that faces the sun' },

  // --- Compound puzzles (two or more emoji = the fun ones) ---
  { emoji: '🦁👑', answer: 'lion king', alt: ['the lion king'], hint: 'a Disney movie about a young lion' },
  { emoji: '🕷️🧍', answer: 'spiderman', alt: ['spider man'], hint: 'a superhero who climbs walls' },
  { emoji: '🦇🧍', answer: 'batman', hint: 'a superhero with a cape and a bat symbol' },
  { emoji: '🌟🐟', answer: 'starfish', alt: ['star fish'], hint: 'a sea creature shaped like a star' },
  { emoji: '🦷🧚', answer: 'tooth fairy', hint: 'leaves money under your pillow' },
  { emoji: '🐮👦', answer: 'cowboy', hint: 'rides horses in the wild west' },
  { emoji: '🐌📧', answer: 'snail mail', hint: 'a slow way to send letters' },
  { emoji: '🌽🐶', answer: 'corn dog', alt: ['corndog'], hint: 'a sausage on a stick in batter' },
  { emoji: '🐢🥷', answer: 'ninja turtle', alt: ['ninja turtles', 'teenage mutant ninja turtle'], hint: 'reptiles who fight crime' },
  { emoji: '❄️👸', answer: 'frozen', alt: ['elsa'], hint: 'a movie about a princess who makes ice' },
  { emoji: '🐠🔍', answer: 'finding nemo', alt: ['nemo'], hint: 'a movie about a lost clownfish' },
  { emoji: '🌙🚶', answer: 'moonwalk', hint: 'a famous backwards dance move' },
  { emoji: '🐍🪜', answer: 'snakes and ladders', alt: ['snakes ladders'], hint: 'a board game with dice' },
  { emoji: '🎩🐰', answer: 'magic trick', alt: ['magician', 'magic'], hint: 'pull a rabbit out of it' },
  { emoji: '🥛🍪', answer: 'milk and cookies', alt: ['milk cookies'], hint: 'a bedtime snack for Santa' },
  { emoji: '🐱👢', answer: 'puss in boots', hint: 'a cat in a hat with a sword' },
  { emoji: '🦋🥅', answer: 'butterfly net', hint: 'you catch bugs with it' },
  { emoji: '🐭👑', answer: 'mickey mouse', alt: ['mickey'], hint: 'a famous Disney mouse' },
  { emoji: '🐸👑', answer: 'frog prince', hint: 'a fairy tale where a kiss breaks a spell' },
  { emoji: '🍫🏭', answer: 'chocolate factory', hint: 'Willy Wonka owns one' },
  { emoji: '🧙⚡', answer: 'harry potter', hint: 'a wizard boy with a lightning scar' },
  { emoji: '⭐⚔️', answer: 'star wars', alt: ['starwars'], hint: 'a space movie with lightsabers' },
  { emoji: '🚗⚡', answer: 'lightning mcqueen', alt: ['cars'], hint: 'a fast red race car from a movie' },
  { emoji: '🦷🪥', answer: 'toothbrush', hint: 'use it to clean your teeth' },
  { emoji: '🌞🌻', answer: 'sunflower', hint: 'a tall flower named after the sun' },
  { emoji: '👻🏠', answer: 'haunted house', hint: 'a spooky place with ghosts' },
  { emoji: '🐝🐝🐝', answer: 'beehive', alt: ['hive'], hint: 'where lots of bees live' },
  { emoji: '🍞🧈', answer: 'bread and butter', alt: ['toast'], hint: 'spread it and eat it' },
  { emoji: '🐻🍯', answer: 'winnie the pooh', alt: ['pooh', 'pooh bear'], hint: 'a bear who loves honey' },
  { emoji: '👣💧', answer: 'footprints', alt: ['footsteps'], hint: 'marks your feet leave behind' },
  { emoji: '🔥🦊', answer: 'firefox', hint: 'a fox that is on fire (a web browser too)' },
  { emoji: '🌧️🌂', answer: 'rainy day', hint: 'a wet day you need an umbrella' },
  { emoji: '🐺🌕', answer: 'werewolf', hint: 'turns from a person at a full moon' },
  { emoji: '🦸‍♂️', answer: 'superhero', hint: 'saves the day with powers' },
  { emoji: '🎄🎁', answer: 'christmas', hint: 'a December holiday with a tree' },
  { emoji: '🥚🐰', answer: 'easter', hint: 'a spring holiday with an egg hunt' },
  { emoji: '🌝🚶‍♂️', answer: 'man on the moon', hint: 'an astronaut who landed up there' },
  { emoji: '🍎🥧', answer: 'apple pie', hint: 'a sweet baked fruit dessert' },
  { emoji: '🐝🔡', answer: 'spelling bee', hint: 'a contest where you spell words' },
  { emoji: '🌧️🏹', answer: 'rainbow', hint: 'rain plus a bow' },
];

// Pick N puzzles, shuffled fresh each game.
export function pickEmojiPuzzles(n: number): EmojiPuzzle[] {
  return [...EMOJI_PUZZLES].sort(() => Math.random() - 0.5).slice(0, n);
}
