// Year 4/5 (UK) school question bank for Friends Arena games.

export type SchoolCategory = 'maths' | 'science' | 'english' | 'geography' | 'history' | 'fun';

export interface SchoolQuestion {
  category: SchoolCategory;
  questionText: string;
  answers: { answerText: string; isCorrect: boolean }[];
}

export interface PreparedQ {
  text: string;
  options: string[];
  correct: number;
}

export const CATEGORIES: { id: SchoolCategory | 'mix'; label: string; emoji: string }[] = [
  { id: 'mix', label: 'Mega Mix', emoji: '🎲' },
  { id: 'maths', label: 'Maths', emoji: '🔢' },
  { id: 'science', label: 'Science', emoji: '🔬' },
  { id: 'english', label: 'English', emoji: '📚' },
  { id: 'geography', label: 'Geography', emoji: '🗺️' },
  { id: 'history', label: 'History', emoji: '🏰' },
  { id: 'fun', label: 'Fun Facts', emoji: '🌈' },
];

const q = (category: SchoolCategory, questionText: string, correct: string, ...wrong: string[]): SchoolQuestion => ({
  category,
  questionText,
  answers: [{ answerText: correct, isCorrect: true }, ...wrong.map((w) => ({ answerText: w, isCorrect: false }))],
});

export const SCHOOL_QUESTIONS: SchoolQuestion[] = [
  // ---- MATHS ----
  q('maths', 'What is 7 × 8?', '56', '54', '48', '64'),
  q('maths', 'What is 9 × 6?', '54', '56', '45', '63'),
  q('maths', 'What is 12 × 12?', '144', '124', '132', '154'),
  q('maths', 'What is 8 × 4?', '32', '28', '36', '24'),
  q('maths', 'What is 11 × 7?', '77', '71', '87', '67'),
  q('maths', 'What is half of 90?', '45', '40', '50', '55'),
  q('maths', 'What is a quarter of 100?', '25', '20', '40', '75'),
  q('maths', 'What is ¾ of 20?', '15', '12', '10', '16'),
  q('maths', 'What is 100 − 37?', '63', '73', '67', '53'),
  q('maths', 'What is 25 + 48?', '73', '63', '83', '75'),
  q('maths', 'What is 144 ÷ 12?', '12', '10', '14', '16'),
  q('maths', 'How many minutes are in 1¼ hours?', '75', '65', '85', '90'),
  q('maths', 'What number is the Roman numeral XII?', '12', '7', '11', '14'),
  q('maths', 'What is the Roman numeral for 10?', 'X', 'V', 'L', 'C'),
  q('maths', 'How many degrees are in a right angle?', '90', '45', '180', '100'),
  q('maths', 'The angles inside a triangle add up to…?', '180°', '90°', '360°', '270°'),
  q('maths', 'How many sides does a hexagon have?', '6', '5', '7', '8'),
  q('maths', 'How many faces does a cube have?', '6', '4', '8', '12'),
  q('maths', 'What comes next: 6, 12, 18, 24, …?', '30', '28', '32', '36'),
  q('maths', 'How many metres are in 1 kilometre?', '1,000', '100', '10', '500'),
  // ---- SCIENCE ----
  q('science', 'At what temperature does water freeze?', '0°C', '10°C', '32°C', '100°C'),
  q('science', 'At what temperature does water boil?', '100°C', '50°C', '90°C', '200°C'),
  q('science', 'When a solid turns into a liquid, it is called…?', 'Melting', 'Freezing', 'Evaporating', 'Condensing'),
  q('science', 'When a liquid turns into a gas, it is called…?', 'Evaporation', 'Melting', 'Freezing', 'Condensation'),
  q('science', 'When a gas turns back into a liquid, it is called…?', 'Condensation', 'Evaporation', 'Melting', 'Boiling'),
  q('science', 'Which organ pumps blood around your body?', 'The heart', 'The brain', 'The lungs', 'The stomach'),
  q('science', 'How many bones are in an adult human body?', '206', '106', '306', '86'),
  q('science', 'What is the largest organ of the human body?', 'The skin', 'The heart', 'The brain', 'The liver'),
  q('science', 'How do plants make their own food?', 'Photosynthesis', 'Respiration', 'Digestion', 'Evaporation'),
  q('science', 'Which gas do plants take in from the air?', 'Carbon dioxide', 'Oxygen', 'Helium', 'Hydrogen'),
  q('science', 'Which gas do humans need to breathe in?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium'),
  q('science', 'How long does Earth take to orbit the Sun?', 'One year', 'One day', 'One month', 'One week'),
  q('science', 'Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars'),
  q('science', 'Which planet is known as the Red Planet?', 'Mars', 'Jupiter', 'Venus', 'Saturn'),
  q('science', 'What force pulls things down to the ground?', 'Gravity', 'Friction', 'Magnetism', 'Air resistance'),
  q('science', 'For electricity to flow, a circuit must be…?', 'Complete (closed)', 'Broken', 'Wooden', 'Wet'),
  q('science', 'Which material is a good conductor of electricity?', 'Copper', 'Wood', 'Plastic', 'Rubber'),
  q('science', 'Sound is made when something…?', 'Vibrates', 'Glows', 'Melts', 'Floats'),
  q('science', 'An animal that only eats plants is called a…?', 'Herbivore', 'Carnivore', 'Omnivore', 'Predator'),
  q('science', 'An animal that is active at night is called…?', 'Nocturnal', 'Diurnal', 'Hibernating', 'Migrating'),
  // ---- ENGLISH ----
  q('english', 'A word that names a person, place or thing is a…?', 'Noun', 'Verb', 'Adjective', 'Adverb'),
  q('english', 'A doing or action word is called a…?', 'Verb', 'Noun', 'Adjective', 'Pronoun'),
  q('english', 'A word that describes a noun is an…?', 'Adjective', 'Adverb', 'Verb', 'Article'),
  q('english', 'A word that describes a verb is an…?', 'Adverb', 'Adjective', 'Noun', 'Pronoun'),
  q('english', 'Which word is a synonym of "happy"?', 'Joyful', 'Sad', 'Angry', 'Sleepy'),
  q('english', 'What is the opposite of "hot"?', 'Cold', 'Warm', 'Boiling', 'Sunny'),
  q('english', 'What is the plural of "child"?', 'Children', 'Childs', 'Childes', 'Childrens'),
  q('english', 'What is the plural of "mouse"?', 'Mice', 'Mouses', 'Mouse', 'Mices'),
  q('english', 'What is the past tense of "run"?', 'Ran', 'Runned', 'Running', 'Runs'),
  q('english', 'What is the past tense of "go"?', 'Went', 'Goed', 'Gone to', 'Going'),
  q('english', 'Which spelling is correct?', 'Because', 'Becuase', 'Becose', 'Beecause'),
  q('english', 'Which spelling is correct?', 'Beautiful', 'Beutiful', 'Beautifull', 'Butiful'),
  q('english', 'Which spelling is correct?', 'Wednesday', 'Wensday', 'Wedensday', 'Wednessday'),
  q('english', '"___ going to the park." Which word fits?', "They're", 'Their', 'There', 'Theyre'),
  q('english', 'Which punctuation mark ends a question?', 'Question mark (?)', 'Full stop (.)', 'Comma (,)', 'Exclamation mark (!)'),
  q('english', 'What is the contraction of "do not"?', "Don't", "Doesn't", "Didn't", "Won't"),
  q('english', 'The prefix "un-" (like unhappy) means…?', 'Not', 'Very', 'Again', 'Before'),
  q('english', 'The word "football" is an example of a…?', 'Compound word', 'Verb', 'Pronoun', 'Prefix'),
  // ---- GEOGRAPHY ----
  q('geography', 'What is the capital city of England?', 'London', 'Manchester', 'Birmingham', 'Liverpool'),
  q('geography', 'What is the capital city of Scotland?', 'Edinburgh', 'Glasgow', 'Aberdeen', 'Dundee'),
  q('geography', 'What is the capital city of Wales?', 'Cardiff', 'Swansea', 'Newport', 'Wrexham'),
  q('geography', 'What is the capital city of France?', 'Paris', 'Lyon', 'Nice', 'Marseille'),
  q('geography', 'What is the capital city of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia'),
  q('geography', 'What is the longest river in the UK?', 'River Severn', 'River Thames', 'River Trent', 'River Mersey'),
  q('geography', 'Which river flows through London?', 'The Thames', 'The Severn', 'The Tyne', 'The Avon'),
  q('geography', 'What is the highest mountain in the UK?', 'Ben Nevis', 'Snowdon', 'Scafell Pike', 'Helvellyn'),
  q('geography', 'How many continents are there?', '7', '5', '6', '8'),
  q('geography', 'What is the largest continent?', 'Asia', 'Africa', 'Europe', 'North America'),
  q('geography', 'What is the largest ocean?', 'Pacific Ocean', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean'),
  q('geography', 'Which continent is the coldest?', 'Antarctica', 'Europe', 'Asia', 'South America'),
  q('geography', 'How many countries make up the United Kingdom?', '4', '3', '5', '2'),
  q('geography', 'What is the UK flag called?', 'The Union Jack', 'The St George Cross', 'The Royal Flag', 'The Britannia'),
  q('geography', 'What is the largest hot desert in the world?', 'The Sahara', 'The Gobi', 'The Outback', 'The Kalahari'),
  q('geography', 'Kangaroos live in the wild in which country?', 'Australia', 'Brazil', 'India', 'South Africa'),
  q('geography', 'The Eiffel Tower is in which city?', 'Paris', 'London', 'Rome', 'New York'),
  q('geography', 'The Great Pyramids of Giza are in which country?', 'Egypt', 'Greece', 'Mexico', 'China'),
  // ---- HISTORY ----
  q('history', 'In which year was the Great Fire of London?', '1666', '1066', '1766', '1966'),
  q('history', 'Where did the Great Fire of London start?', 'A bakery in Pudding Lane', 'A castle', 'A church', 'A ship on the Thames'),
  q('history', 'The Romans came from which country?', 'Italy', 'Greece', 'Spain', 'Egypt'),
  q('history', 'What wall did the Romans build in northern England?', "Hadrian's Wall", 'The Great Wall', "Offa's Dyke", 'The London Wall'),
  q('history', 'The Vikings came from which lands?', 'Scandinavia', 'France', 'Italy', 'Spain'),
  q('history', 'What were Viking ships called?', 'Longships', 'Galleons', 'Canoes', 'Ferries'),
  q('history', 'Which Tudor king had six wives?', 'Henry VIII', 'Henry VII', 'Edward VI', 'Richard III'),
  q('history', 'Which famous Tudor queen was Henry VIII\'s daughter?', 'Elizabeth I', 'Victoria', 'Mary Queen of Scots', 'Anne'),
  q('history', 'The Ancient Egyptians built which famous structures?', 'Pyramids', 'Castles', 'Cathedrals', 'Lighthouses'),
  q('history', 'What was an Ancient Egyptian ruler called?', 'A pharaoh', 'A king', 'An emperor', 'A sultan'),
  q('history', 'What is Ancient Egyptian picture writing called?', 'Hieroglyphics', 'Calligraphy', 'Runes', 'Graffiti'),
  q('history', 'Which river was most important to Ancient Egypt?', 'The Nile', 'The Amazon', 'The Thames', 'The Tiber'),
  q('history', 'Who was the famous boy king of Egypt?', 'Tutankhamun', 'Julius Caesar', 'Alexander', 'Rameses'),
  q('history', 'Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Lightyear', 'Yuri Gagarin', 'Tim Peake'),
  q('history', 'In WW2, children moved from cities to the countryside were called…?', 'Evacuees', 'Refugees', 'Pioneers', 'Scouts'),
  q('history', 'Which queen ruled Britain for most of the 1800s?', 'Queen Victoria', 'Queen Elizabeth II', 'Queen Anne', 'Queen Mary'),
  // ---- FUN FACTS ----
  q('fun', 'How many days are in a week?', '7', '5', '6', '8'),
  q('fun', 'How many colours are in a rainbow?', '7', '5', '6', '8'),
  q('fun', 'How many legs does a spider have?', '8', '6', '10', '4'),
  q('fun', 'How many legs does an insect have?', '6', '8', '4', '10'),
  q('fun', 'What is the biggest animal that has ever lived?', 'The blue whale', 'The elephant', 'The T-rex', 'The giraffe'),
  q('fun', 'What is the fastest land animal?', 'The cheetah', 'The lion', 'The horse', 'The greyhound'),
  q('fun', 'What is the tallest animal in the world?', 'The giraffe', 'The elephant', 'The ostrich', 'The camel'),
  q('fun', 'What do bees make?', 'Honey', 'Jam', 'Butter', 'Sugar'),
  q('fun', 'What is a baby dog called?', 'A puppy', 'A kitten', 'A cub', 'A foal'),
  q('fun', 'What is a baby sheep called?', 'A lamb', 'A calf', 'A kid', 'A piglet'),
  q('fun', 'What is a baby frog called?', 'A tadpole', 'A froglet', 'A minnow', 'A newt'),
  q('fun', 'How many players are on a football team (on the pitch)?', '11', '10', '12', '9'),
  q('fun', 'How many rings are on the Olympic flag?', '5', '4', '6', '7'),
  q('fun', 'What does a caterpillar turn into?', 'A butterfly', 'A bee', 'A dragonfly', 'A ladybird'),
  q('fun', 'Which bird cannot fly?', 'The penguin', 'The owl', 'The robin', 'The seagull'),
  q('fun', 'How many zeros are in one thousand?', '3', '2', '4', '5'),

  // ===== EXPANSION PACK — more variety so nobody can memorise the set =====
  // ---- MATHS ----
  q('maths', 'What is 6 × 7?', '42', '36', '48', '40'),
  q('maths', 'What is 8 × 8?', '64', '54', '72', '60'),
  q('maths', 'What is 9 × 9?', '81', '72', '91', '99'),
  q('maths', 'What is 7 × 7?', '49', '42', '56', '47'),
  q('maths', 'What is 3 × 12?', '36', '24', '33', '39'),
  q('maths', 'What is 50 ÷ 5?', '10', '5', '15', '8'),
  q('maths', 'What is 81 ÷ 9?', '9', '8', '7', '11'),
  q('maths', 'What is 1000 − 250?', '750', '850', '650', '700'),
  q('maths', 'What is 365 + 135?', '500', '490', '510', '400'),
  q('maths', 'What is double 45?', '90', '80', '85', '95'),
  q('maths', 'What is half of 64?', '32', '34', '30', '28'),
  q('maths', 'What is ¾ written as a decimal?', '0.75', '0.34', '0.5', '0.25'),
  q('maths', 'What is ½ written as a decimal?', '0.5', '0.2', '0.12', '0.25'),
  q('maths', 'What is 0.1 + 0.2?', '0.3', '0.12', '0.21', '0.03'),
  q('maths', 'How many millimetres are in 1 centimetre?', '10', '100', '5', '1,000'),
  q('maths', 'How many centimetres are in 1 metre?', '100', '10', '1,000', '50'),
  q('maths', 'How many grams are in 1 kilogram?', '1,000', '100', '10', '500'),
  q('maths', 'How many seconds are in a minute?', '60', '100', '30', '24'),
  q('maths', 'How many hours are in a day?', '24', '12', '60', '48'),
  q('maths', 'How many sides does a pentagon have?', '5', '6', '4', '7'),
  q('maths', 'How many sides does an octagon have?', '8', '6', '7', '10'),
  q('maths', 'What is the perimeter of a square with 5 cm sides?', '20 cm', '25 cm', '10 cm', '15 cm'),
  q('maths', 'What is the area of a rectangle 4 cm by 3 cm?', '12 cm²', '7 cm²', '14 cm²', '24 cm²'),
  q('maths', 'What is the next prime number after 7?', '11', '9', '10', '8'),
  q('maths', 'Which of these is a factor of 24?', '6', '5', '7', '9'),
  q('maths', 'What comes next: 5, 10, 15, 20, …?', '25', '24', '30', '22'),
  // ---- SCIENCE ----
  q('science', 'What are the three states of matter?', 'Solid, liquid, gas', 'Hot, warm, cold', 'Rock, water, air', 'Big, medium, small'),
  q('science', 'Which part of a plant takes in water from the soil?', 'The roots', 'The leaves', 'The flower', 'The petals'),
  q('science', 'Which part of a plant makes the seeds?', 'The flower', 'The roots', 'The stem', 'The leaves'),
  q('science', 'Which part of a plant makes food using sunlight?', 'The leaves', 'The roots', 'The stem', 'The seeds'),
  q('science', 'What do we call animals that have a backbone?', 'Vertebrates', 'Invertebrates', 'Predators', 'Herbivores'),
  q('science', 'Which animal group do humans belong to?', 'Mammals', 'Reptiles', 'Birds', 'Amphibians'),
  q('science', 'Frogs and newts belong to which animal group?', 'Amphibians', 'Reptiles', 'Mammals', 'Fish'),
  q('science', 'Which body part do you use to breathe?', 'The lungs', 'The heart', 'The kidneys', 'The brain'),
  q('science', 'Flat teeth at the back used for grinding food are called…?', 'Molars', 'Incisors', 'Canines', 'Fangs'),
  q('science', 'What do we call the path the Moon takes around the Earth?', 'An orbit', 'A spin', 'A phase', 'A shadow'),
  q('science', 'How long does the Earth take to spin around once?', '24 hours', '1 year', '1 month', '12 hours'),
  q('science', 'Why do we have day and night?', 'The Earth spins', 'The Sun moves round Earth', 'The Moon blocks the Sun', 'Clouds cover the Sun'),
  q('science', 'The Sun is actually a…?', 'Star', 'Planet', 'Moon', 'Comet'),
  q('science', 'Which is the largest planet in our Solar System?', 'Jupiter', 'Saturn', 'Earth', 'Neptune'),
  q('science', 'How many planets are in our Solar System?', '8', '9', '7', '10'),
  q('science', 'A shadow is made when light is…?', 'Blocked', 'Reflected', 'Bent', 'Coloured'),
  q('science', 'Which of these is a magnetic material?', 'Iron', 'Wood', 'Plastic', 'Glass'),
  q('science', 'What force slows things down when they rub together?', 'Friction', 'Gravity', 'Magnetism', 'Electricity'),
  q('science', 'What does a seed need to start growing?', 'Water, warmth and air', 'Only sunlight', 'Only soil', 'Nothing at all'),
  q('science', 'Which of these is NOT a source of its own light?', 'The Moon', 'The Sun', 'A torch', 'A candle'),
  q('science', 'Rain, snow and hail falling from clouds is called…?', 'Precipitation', 'Evaporation', 'Condensation', 'Filtration'),
  q('science', 'The water cycle is powered by heat from the…?', 'Sun', 'Moon', 'Wind', 'Sea'),
  q('science', 'An animal that eats both plants and meat is a…?', 'Omnivore', 'Herbivore', 'Carnivore', 'Predator'),
  q('science', 'Which of these will a magnet attract?', 'A steel paperclip', 'A plastic ruler', 'A wooden pencil', 'A glass marble'),
  q('science', 'What do we call a baby plant growing from a seed?', 'A seedling', 'A cub', 'A larva', 'A foal'),
  q('science', 'Which sense organ do you use to hear?', 'Ears', 'Eyes', 'Nose', 'Tongue'),
  // ---- ENGLISH ----
  q('english', 'A word that replaces a noun (he, she, it) is a…?', 'Pronoun', 'Adverb', 'Adjective', 'Conjunction'),
  q('english', 'Words like "and", "but" and "or" are called…?', 'Conjunctions', 'Pronouns', 'Adjectives', 'Nouns'),
  q('english', 'Names of people and places (like London) begin with a…?', 'Capital letter', 'Small letter', 'Number', 'Comma'),
  q('english', 'What is the opposite of "begin"?', 'End', 'Start', 'Open', 'Go'),
  q('english', 'Which word is a synonym of "big"?', 'Large', 'Tiny', 'Thin', 'Quiet'),
  q('english', 'What is the plural of "foot"?', 'Feet', 'Foots', 'Feets', 'Footes'),
  q('english', 'What is the plural of "tooth"?', 'Teeth', 'Tooths', 'Teeths', 'Toothes'),
  q('english', 'What is the plural of "leaf"?', 'Leaves', 'Leafs', 'Leafes', 'Leave'),
  q('english', 'What is the past tense of "eat"?', 'Ate', 'Eated', 'Eaten', 'Eats'),
  q('english', 'What is the past tense of "swim"?', 'Swam', 'Swimmed', 'Swimed', 'Swims'),
  q('english', 'Which word is spelled correctly?', 'Friend', 'Freind', 'Frend', 'Friynd'),
  q('english', 'Which word is spelled correctly?', 'Separate', 'Seperate', 'Separete', 'Sepparate'),
  q('english', 'Which word is spelled correctly?', 'Necessary', 'Neccessary', 'Necesary', 'Neccesary'),
  q('english', 'A group of words with a capital letter and a full stop is a…?', 'Sentence', 'Paragraph', 'Syllable', 'Letter'),
  q('english', 'Which mark shows excitement or shouting?', 'Exclamation mark (!)', 'Comma (,)', 'Full stop (.)', 'Colon (:)'),
  q('english', 'Which marks show that someone is speaking?', 'Speech marks', 'Brackets', 'Hyphens', 'Apostrophes'),
  q('english', 'What does the contraction "can\'t" stand for?', 'Cannot', 'Could not', 'Can it', 'Can to'),
  q('english', 'The suffix "-ful" (like "joyful") means…?', 'Full of', 'Without', 'Before', 'Again'),
  q('english', 'The prefix "re-" (like "redo") means…?', 'Again', 'Not', 'Before', 'Under'),
  q('english', 'A word that copies a sound, like "buzz", is called…?', 'Onomatopoeia', 'A simile', 'A metaphor', 'A rhyme'),
  q('english', 'Saying someone is "as brave as a lion" is a…?', 'Simile', 'Metaphor', 'Verb', 'Pronoun'),
  q('english', 'Which word is a noun?', 'Table', 'Quickly', 'Jump', 'Happy'),
  q('english', 'Which word is an adjective?', 'Sparkly', 'Run', 'Slowly', 'Dog'),
  q('english', 'Which word is an adverb?', 'Quietly', 'Cat', 'Green', 'Sing'),
  q('english', 'A naming word for a feeling, like "kindness", is which type of noun?', 'Abstract noun', 'Proper noun', 'Verb', 'Adverb'),
  // ---- GEOGRAPHY ----
  q('geography', 'What is the capital city of Italy?', 'Rome', 'Milan', 'Venice', 'Naples'),
  q('geography', 'What is the capital city of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Frankfurt'),
  q('geography', 'What is the capital city of the United States?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'),
  q('geography', 'What is the capital city of Japan?', 'Tokyo', 'Kyoto', 'Osaka', 'Seoul'),
  q('geography', 'What is the capital city of Ireland?', 'Dublin', 'Belfast', 'Cork', 'Galway'),
  q('geography', 'Which country is shaped like a boot?', 'Italy', 'Spain', 'France', 'Greece'),
  q('geography', 'Mount Everest is the world\'s highest…?', 'Mountain', 'Volcano', 'Waterfall', 'River'),
  q('geography', 'Which is the smallest continent?', 'Australia (Oceania)', 'Europe', 'Antarctica', 'Asia'),
  q('geography', 'What do we call a dry area of sand with very little water?', 'A desert', 'A forest', 'A jungle', 'A swamp'),
  q('geography', 'The imaginary line around the middle of the Earth is the…?', 'Equator', 'Prime Meridian', 'Tropic', 'Axis'),
  q('geography', 'The North Pole is found in which region?', 'The Arctic', 'The Antarctic', 'The Sahara', 'The Amazon'),
  q('geography', 'Which ocean lies to the west of the UK and Ireland?', 'The Atlantic Ocean', 'The Pacific Ocean', 'The Indian Ocean', 'The Arctic Ocean'),
  q('geography', 'A person who makes maps is called a…?', 'Cartographer', 'Geologist', 'Astronomer', 'Navigator'),
  q('geography', 'On a compass, which direction is opposite North?', 'South', 'East', 'West', 'Up'),
  q('geography', 'What are the four main compass directions?', 'North, South, East, West', 'Up, Down, Left, Right', 'Hot, Cold, Wet, Dry', 'Front, Back, Side, Top'),
  q('geography', 'A sudden shaking of the ground is called an…?', 'Earthquake', 'Avalanche', 'Eruption', 'Tornado'),
  q('geography', 'Which country has the most people in the world?', 'India', 'China', 'USA', 'Russia'),
  q('geography', 'The Statue of Liberty stands in which city?', 'New York', 'London', 'Paris', 'Sydney'),
  q('geography', 'The Sydney Opera House is in which country?', 'Australia', 'Austria', 'New Zealand', 'Canada'),
  q('geography', 'Which is the largest country in the world by area?', 'Russia', 'China', 'Canada', 'USA'),
  q('geography', 'A small piece of land surrounded by water is called…?', 'An island', 'A peninsula', 'A bay', 'A valley'),
  q('geography', 'What do we call the usual weather of a place over many years?', 'Climate', 'Forecast', 'Season', 'Temperature'),
  q('geography', 'The Leaning Tower is found in which Italian city?', 'Pisa', 'Rome', 'Milan', 'Turin'),
  q('geography', 'Polar bears live in the wild near which pole?', 'The North Pole', 'The South Pole', 'The Equator', 'The Sahara'),
  q('geography', 'Penguins live in the wild mostly near which pole?', 'The South Pole', 'The North Pole', 'The Equator', 'The Arctic'),
  // ---- HISTORY ----
  q('history', 'Stone Age people made their tools from…?', 'Stone', 'Plastic', 'Iron', 'Gold'),
  q('history', 'Which age came straight after the Stone Age?', 'The Bronze Age', 'The Iron Age', 'The Middle Ages', 'The Space Age'),
  q('history', 'Stonehenge is a famous ancient monument made of…?', 'Giant stones', 'Wood', 'Bricks', 'Metal'),
  q('history', 'The Ancient Greeks held the very first…?', 'Olympic Games', 'World Cup', 'Space mission', 'Marathon race only'),
  q('history', 'Which Ancient Greek city is famous for inventing democracy?', 'Athens', 'Sparta', 'Troy', 'Rome'),
  q('history', 'Roman foot soldiers were known as…?', 'Legionaries', 'Knights', 'Samurai', 'Vikings'),
  q('history', 'Roman roads were famous for being…?', 'Very straight', 'Very curvy', 'Made of gold', 'Underwater'),
  q('history', 'Which Roman leader first invaded Britain in 55 BC?', 'Julius Caesar', 'Augustus', 'Nero', 'Hadrian'),
  q('history', 'The Anglo-Saxons arrived in Britain after which people left?', 'The Romans', 'The Vikings', 'The Tudors', 'The Normans'),
  q('history', 'In 1066, who won the Battle of Hastings?', 'William the Conqueror', 'King Harold', 'Henry VIII', 'Julius Caesar'),
  q('history', 'After 1066 the Normans built many strong…?', 'Castles', 'Pyramids', 'Temples', 'Skyscrapers'),
  q('history', 'Christopher Columbus sailed across which ocean in 1492?', 'The Atlantic', 'The Pacific', 'The Indian', 'The Arctic'),
  q('history', 'The Wright brothers are famous for inventing the…?', 'Aeroplane', 'Car', 'Telephone', 'Television'),
  q('history', 'Who invented the telephone?', 'Alexander Graham Bell', 'Thomas Edison', 'Isaac Newton', 'Albert Einstein'),
  q('history', 'Who described gravity after watching an apple fall?', 'Isaac Newton', 'Albert Einstein', 'Charles Darwin', 'Galileo'),
  q('history', 'The Titanic sank in 1912 after hitting an…?', 'Iceberg', 'Whale', 'Rock', 'Island'),
  q('history', 'Florence Nightingale is famous for being a…?', 'Nurse', 'Queen', 'Pilot', 'Painter'),
  q('history', 'Mary Seacole, who helped soldiers in the Crimean War, came from…?', 'Jamaica', 'France', 'Egypt', 'Italy'),
  q('history', 'The first ever satellite to orbit Earth was called…?', 'Sputnik', 'Apollo', 'Voyager', 'Hubble'),
  q('history', 'The Ancient Egyptians preserved dead bodies as…?', 'Mummies', 'Statues', 'Robots', 'Paintings'),
  q('history', 'The Great Wall is found in which country?', 'China', 'India', 'Egypt', 'Italy'),
  q('history', 'Which explorer was first to reach the South Pole?', 'Roald Amundsen', 'Neil Armstrong', 'Marco Polo', 'Francis Drake'),
  q('history', 'Castles were often surrounded by water in a…?', 'Moat', 'Pond', 'Stream', 'Lake'),
  q('history', 'A knight wore protective metal clothing called…?', 'Armour', 'A toga', 'A robe', 'A cloak'),
  q('history', 'In which century did World War 2 take place?', 'The 20th century (1900s)', 'The 19th century (1800s)', 'The 17th century (1600s)', 'The 21st century (2000s)'),
  // ---- FUN FACTS ----
  q('fun', 'What is a baby cat called?', 'A kitten', 'A puppy', 'A cub', 'A chick'),
  q('fun', 'What is a baby cow called?', 'A calf', 'A lamb', 'A foal', 'A kid'),
  q('fun', 'What is a baby horse called?', 'A foal', 'A calf', 'A cub', 'A joey'),
  q('fun', 'What is a baby kangaroo called?', 'A joey', 'A cub', 'A kit', 'A pup'),
  q('fun', 'What is a group of lions called?', 'A pride', 'A pack', 'A herd', 'A flock'),
  q('fun', 'What is a group of wolves called?', 'A pack', 'A pride', 'A school', 'A swarm'),
  q('fun', 'What is a group of fish called?', 'A school', 'A pack', 'A herd', 'A pride'),
  q('fun', 'How many hearts does an octopus have?', '3', '1', '2', '8'),
  q('fun', 'What is the largest land animal?', 'The elephant', 'The rhino', 'The hippo', 'The giraffe'),
  q('fun', 'Which slow animal is famous for hanging in trees?', 'The sloth', 'The koala', 'The turtle', 'The panda'),
  q('fun', 'How many months have 31 days?', '7', '5', '6', '12'),
  q('fun', 'How many sides does a triangle have?', '3', '4', '5', '6'),
  q('fun', 'What do you call a shape with four equal sides?', 'A square', 'A circle', 'A triangle', 'A rectangle'),
  q('fun', 'What is frozen water called?', 'Ice', 'Steam', 'Mist', 'Rain'),
  q('fun', 'What do you call a doctor for animals?', 'A vet', 'A nurse', 'A farmer', 'A zookeeper'),
  q('fun', 'Which is the only mammal that can truly fly?', 'The bat', 'The eagle', 'The penguin', 'The flying squirrel'),
  q('fun', 'What is the hardest natural substance on Earth?', 'Diamond', 'Gold', 'Iron', 'Glass'),
  q('fun', 'How many colours are on a traffic light?', '3', '2', '4', '5'),
  q('fun', 'Which planet do we live on?', 'Earth', 'Mars', 'Venus', 'Jupiter'),
  q('fun', 'What shape does a full Moon look like?', 'A circle', 'A triangle', 'A square', 'A star'),
  q('fun', 'How many legs does a butterfly have?', '6', '8', '4', '2'),
  q('fun', 'What does a caterpillar build to transform?', 'A chrysalis', 'A nest', 'A web', 'A shell'),
  q('fun', 'Which tall grass is a panda’s favourite food?', 'Bamboo', 'Wheat', 'Corn', 'Reeds'),
  q('fun', 'Which animal is known as the King of the Jungle?', 'The lion', 'The tiger', 'The elephant', 'The gorilla'),
  q('fun', 'How many days are there in a leap year?', '366', '365', '364', '367'),
];

export function pickQuestions(category: SchoolCategory | 'mix', count: number): PreparedQ[] {
  const pool = category === 'mix' ? SCHOOL_QUESTIONS : SCHOOL_QUESTIONS.filter((x) => x.category === category);
  return [...pool]
    .sort(() => Math.random() - 0.5)
    .slice(0, count)
    .map((qu) => {
      const answers = [...qu.answers].sort(() => Math.random() - 0.5);
      return {
        text: qu.questionText,
        options: answers.map((a) => a.answerText),
        correct: answers.findIndex((a) => a.isCorrect),
      };
    });
}
